language: node_js
node_js:
  - "11.0"
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  - npm install
  - npm run build
deploy:
  provider: heroku
  api_key:
    secure: "0ce5bd93-fb16-4697-9738-869e4ca19a16"
  app: indiv-proj-app
